# Generated by Django 5.2.8 on 2026-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funiture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input Email',
                'verbose_name_plural': 'Input Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
